name: Release

on:
  release:
    types: [published]

jobs:
  linux:
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64, arm64]
    env:
      GOARCH: ${{ matrix.goarch }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential

      - name: Build CPU binary
        run: |
          git submodule update --init --recursive
          go generate ./...
          mkdir -p ${{ matrix.goarch }}-ollama
          go build -o ${{ matrix.goarch }}-ollama/ollama
          cp llm/llama.cpp/ggml/build/bin/server ${{ matrix.goarch }}-ollama/ollama

      - name: Zip the build
        run: zip -r ${{ matrix.goarch }}-ollama.zip ${{ matrix.goarch }}-ollama/

      - run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          gh release view ${TAG_NAME} || exit 1
          gh release upload ${TAG_NAME} ${{ matrix.goarch }}-ollama.zip
        env:
          GH_TOKEN: ${{ github.token }}
