name: Release

on:
  release:
    types: [published]

jobs:
  linux:
    permissions: write-all
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.docker_image }}
    strategy:
      matrix:
        docker_image: ['amd64/golang:1.21.0', 'arm64v8/golang:1.21.0']
        goarch: ['amd64', 'arm64']
    env:
      GOARCH: ${{ matrix.goarch }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup dependencies
        run: |
          apt-get update
          apt-get install -y build-essential

      - name: Build CPU binary
        run: |
          git submodule update --init --recursive
          go generate ./...
          mkdir -p ${{ matrix.goarch }}-ollama
          go build -o ${{ matrix.goarch }}-ollama/ollama
          cp llm/llama.cpp/ggml/build/bin/server ${{ matrix.goarch }}-ollama

      - name: Zip the build
        run: zip -r ${{ matrix.goarch }}-ollama.zip ${{ matrix.goarch }}-ollama/

      - run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          gh release view ${TAG_NAME} || exit 1
          gh release upload ${TAG_NAME} ${{ matrix.goarch }}-ollama.zip
        env:
          GH_TOKEN: ${{ github.token }}
