name: Release

on:
  push:
    branches:
      - main

jobs:
  cuda-build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        cuda: ['11.7.0']
    steps:
      - uses: jimver/cuda-toolkit@v0.2.11
        with:
          cuda: ${{ matrix.cuda }}
          method: network
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Install Linux build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake
          nvcc --version
      - name: Generate CUDA runners
        run: |
          go generate ./...
      - name: Zip and upload CUDA output
        run: |
          zip -r cuda-${{ matrix.cuda }}.zip ./llm/llama.cpp/*/build/
      - uses: actions/upload-artifact@v2
        with:
          name: cuda-${{ matrix.cuda }}
          path: cuda-${{ matrix.cuda }}.zip

  ollama-build:
    needs: [cuda-build]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Generate CPU runners
        run: |
          go generate ./...

      - name: Download CUDA 11 runner
        uses: actions/download-artifact@v2
        with:
          name: cuda-11.7.0
      - run: |
          unzip cuda-11.7.0 -d ./temp-cuda-11
          mkdir -p ./llm/llama.cpp/ggml/build/cuda-11.7.0/bin
          mkdir -p ./llm/llama.cpp/gguf/build/cuda-11.7.0/bin
          mv ./temp-cuda-11/llm/llama.cpp/ggml/build/cuda-11.7.0/bin/server ./llm/llama.cpp/ggml/build/cuda-11.7.0/bin/server
          mv ./temp-cuda-11/llm/llama.cpp/gguf/build/cuda-11.7.0/bin/server ./llm/llama.cpp/ggml/build/cuda-11.7.0/bin/server
          rm -rf ./temp-cuda-11

      - name: Build with all packaged in runners
        run: |
          go build -o ollama
        env:
          GOFLAGS: >-
            '-ldflags=-w -s
              "-X=github.com/brucemacd/ollama/version.Version=${{ github.ref_name }}"

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: ollama-amd64
          path: ollama-amd64
