name: Release

on:
  release:
    types: [published]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64, arm64]
    env:
      GOARCH: ${{ matrix.goarch }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential

      - name: Build CPU binary
        run: |
          git submodule update --init --recursive
          go generate ./...
          go build -o ${{ matrix.goarch }}/ollama

      - uses: actions/upload-artifact@v3
        with:
          name: ollama-linux-${{ matrix.goarch }}
          path: ${{ matrix.goarch }}/ollama

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ matrix.goarch }}/ollama
          asset_name: ollama-linux-${{ matrix.goarch }}
          asset_content_type: application/octet-stream
