name: Release

on:
  create:
    tags:
      - '*'

jobs:
  linux:
    runs-on: ubuntu-latest
    env:
      VERSION: '0.0'
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential

      - name: Build CPU binary
        run: |
          git submodule update --init --recursive
          go generate ./...
          go build -o ollama

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Upload Binary to Release
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          gh release upload ${{ github.ref }} ollama
