name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Download NVCC
        run: |
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.1-1_all.deb
          sudo dpkg -i cuda-keyring_1.1-1_all.deb
          sudo apt-get update
          sudo apt-get -y install cuda-11-4
          sudo apt-get -y install cuda-12-1
      - name: Build with all packaged in runners
        run: |
          ls /usr/local
          go generate ./...
          go build -o ollama -ldflags="-w -s -X github.com/brucemacd/ollama/version.Version=${{ github.ref_name }}"
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: ollama-amd64
          path: ollama
