name: Release

on:
  release:
    types: [published]

jobs:
  linux:
    runs-on: ubuntu-latest
    env:
      VERSION: '0.0'
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential

      - name: Build CPU binary
        run: |
          git submodule update --init --recursive
          go generate ./...
          go build -o ollama

      - uses: actions/upload-artifact@v3
        with:
          name: ollama-linux
          path: ollama

      # - name: Upload Release Asset
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ github.event.release.upload_url }}
